
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12

[general]
live_config_reload = true
import = [
  "/home/plof/.config/alacritty/fonts.toml",
]
