[colors.primary]
background = '#161217'
foreground = '#e9e0e7'
 
[colors.cursor]
text = '#e9e0e7'
cursor = '#cec3cd' 
 
[colors.vi_mode_cursor]
text = '#161217'
cursor = '#e4b7f2' 
 
[colors.search.matches]
foreground = '#4c444d' 
background = '#f5b7b4' 
 
[colors.search.focused_match]
foreground = '#4c444d' 
background = '#e4b7f2' 
 
[colors.footer_bar]
foreground = '#4c444d' 
background = '#e9e0e7' 
 
[colors.hints.start]
foreground = '#4c444d' 
background = '#d4c0d7' 
 
[colors.hints.end]
foreground = '#4c444d' 
background = '#d4c0d7' 
 
[colors.selection]
text = '#161217'
background = '#e4b7f2'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#e4b7f2' 
yellow = '#765084' 
blue = '#e4b7f2' 
magenta = '#f5b7b4' 
cyan = '#d4c0d7' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
