background #111318
foreground #e2e2e9
cursor #e2e2e9

active_tab_background #1d2024
active_tab_foreground #e2e2e9
inactive_tab_background #111318
inactive_tab_foreground #c4c6cf

color0 #111318
color8 #37393e

color1 #ffb4ab
color9 #93000a

color2 #a8c8ff
color10 #254777

color3 #dcbce1
color11 #563e5c

color4 #bdc7dc
color12 #3e4758

color5 #8e9099
color13 #43474e

color6 #d6e3ff
color14 #a8c8ff

color7 #e2e2e9
color15 #c4c6cf

selection_background #3e4758
selection_foreground #d9e3f8
