background #0e1415
foreground #dde4e4
cursor #dde4e4

active_tab_background #1a2121
active_tab_foreground #dde4e4
inactive_tab_background #0e1415
inactive_tab_foreground #bec8c9

color0 #0e1415
color8 #343a3b

color1 #ffb4ab
color9 #93000a

color2 #80d4d9
color10 #004f53

color3 #b6c7e9
color11 #364764

color4 #b1cccd
color12 #324b4c

color5 #899393
color13 #3f4949

color6 #9cf0f5
color14 #80d4d9

color7 #dde4e4
color15 #bec8c9

selection_background #324b4c
selection_foreground #cce8e9
