foreground              #FFFFFF
background              #1E2226
selection_foreground    #1E2226
selection_background    #FFFFFF
cursor                  #9DA882 
cursor_text_color       #111111

active_tab_foreground     #1E2226
active_tab_background     #5D7253
inactive_tab_foreground   #5D7253
inactive_tab_background   #1E2226

# black
color0      #293D52
color8      #57738F

# red
color1      #F0FFCC
color9      #DCF0AA

# green
color2      #D2FFCC
color10     #B3F0AA

# yellow
color3      #DCFFCC
color11     #C1F0AA

# blue
color4      #9AC0E6
color12     #9AC0E6

# magenta
color5      #A3E69A
color13     #A3E69A

# cyan
color6      #B2E69A
color14     #B2E69A

# white
color7      #F0FFCC
color15     #DCF0AA
