[config]
[templates.quickshell]
input_path = '~/.config/matugen/templates/ImagePath.qml'
output_path = '~/.config/quickshell/lockscreen/ImagePath.qml'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/colors-hyprland.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.wlogout]
input_path = '~/.config/matugen/templates/theme.css'
output_path = '~/.config/wlogout/theme.css'

[templates.Xdefaults]
input_path = '~/.config/matugen/templates/.Xdefaults'
output_path = '~/configs/.Xdefaults'

[templates.name1]
input_path = '~/.config/matugen/templates/test.css'
output_path = "~/test.css"
colors_to_compare = [
    { name = "black", color = "#000000" },
    { name = "red", color = "#ff0000" },
    { name = "maroon", color = "#800000" },
    { name = "yellow", color = "#ffff00" },
    { name = "olive", color = "#808000" },
    { name = "lime", color = "#00ff00" },
    { name = "green", color = "#008000" },
    { name = "aqua", color = "#00ffff" },
    { name = "teal", color = "#008080" },
    { name = "blue", color = "#0000ff" },
    { name = "navy", color = "#000080" },
    { name = "fuchsia", color = "#ff00ff" },
    { name = "purple", color = "#800080" },
]
compare_to = "{{colors.primary.default.hex}}"
pre_hook = 'echo "source color {{colors.source_color.default.hex}}, source image {{image}}, closest color {{closest_color}}"'
post_hook = 'echo "after gen"'

[config.custom_colors]
green = "#00FF00"
red = "#FF0000"
blue = { color = "#0000FF", blend = false }

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim.txt'
output_path = '~/.config/lvim/nvim.txt'
