-- Plugins Configuration
hl.config({
	plugin = {
		-- ["dynamic-cursors"] = {
		--     enabled = true,
		--     mode = "tilt",
		--     tilt = {
		--         limit = 1000,
		--         ["function"] = "negative_quadratic",
		--     },
		--     stretch = {
		--         limit = 1000,
		--         ["function"] = "quadratic",
		--     },
		--     shake = {
		--         enabled = true,
		--         base = 2.5,
		--         threshold = 4.0,
		--         timeout = 2000,
		--         speed = 1.0,
		--         nearest = false,
		--     },
		--     hyprcursor = {
		--         enabled = true,
		--         nearest = false,
		--         resolution = -1,
		--     }
		-- },
		--imgborders = {
		--    enabled = false,
		--    image = "~/configs/hypr/gui.png",
		--    sizes = "4,4,4,4",
		--    insets = "3,3,2,2",
		--    scale = 4,
		--    smooth = false,
		--},
		--hyprbars = {
		--    bar_height = 0,
		--    bar_color = "rgb(1e1e1e)",
		--    ["col.text"] = "rgb(ffffff)",
		--    bar_text_size = 12,
		--    bar_text_font = "Jetbrains Mono Nerd Font Mono Bold",
		--    bar_button_padding = 20,
		--    bar_padding = 10,
		--    bar_precedence_over_border = true,
		--},
		-- touch_gestures = {
		--     sensitivity = 4.0,
		--     workspace_swipe_fingers = 3,
		--     workspace_swipe_edge = "d",
		--     long_press_delay = 100,
		--     resize_on_border_long_press = true,
		--     edge_margin = 30,
		--     emulate_touchpad_swipe = false,
		-- }
	},
})

-- Prueba de configuración funcional (solo hyprbars como prueba)
--if hl.plugin.hyprbars ~= nil then
--    -- Intentamos el patrón funcional con pcall para evitar errores fatales
--    pcall(function()
--        hl.plugin.hyprbars.add_button({
--            bg_color = "rgb(ffff00)",
--            size = 25,
--            icon = "",
--            command = "hyprctl dispatch killactive"
--        })
--    end)
--end
