
[Wallbash]
text               = 392952
subtext            = 4D3A6B
nav-active-text    = 5F4B7D
main               = F9DDF1
sidebar            = F9DDF1
player             = F9DDF1
card               = F9DDF1
shadow             = FFCCF0
main-secondary     = DDAAF0
button             = 4C3A6B
button-secondary   = 5E4B7D
button-active      = 6C578F
button-disabled    = F9DDF1
nav-active         = C4AAF0
play-button        = B69AE6
tab-active         = B79FC0
notification       = F9DDF1
notification-error = F9DDF1
playback-bar       = F9DDF1
misc               = B79FC0

; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous
