
[Wallbash]
text               = FFCCCF
subtext            = F0AAAE
nav-active-text    = E69A9E
main               = 23162D
sidebar            = 23162D
player             = 23162D
card               = 23162D
shadow             = 402952
main-secondary     = 593A6B
button             = F0AAD4
button-secondary   = E69AC7
button-active      = C27AA5
button-disabled    = 23162D
nav-active         = 6B3A57
play-button        = 7D4B69
tab-active         = 442456
notification       = 23162D
notification-error = 23162D
playback-bar       = 23162D
misc               = 442456

; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous
