
[Wallbash]
text               = F0FFCC
subtext            = DCF0AA
nav-active-text    = D0E69A
main               = 1E2226
sidebar            = 1E2226
player             = 1E2226
card               = 1E2226
shadow             = 293D52
main-secondary     = 406B3A
button             = C1F0AA
button-secondary   = B2E69A
button-active      = 91C27A
button-disabled    = 1E2226
nav-active         = 4A6B3A
play-button        = 5B7D4B
tab-active         = 394737
notification       = 1E2226
notification-error = 1E2226
playback-bar       = 1E2226
misc               = 394737

; Description

; text             = main text, playlist names in main field, name of playlist selected in sidebar, headings
; subtext          = text in main buttons in sidebar, playlist names in sidebar, artist names, and mini infos
; nav-active-text  = text in main buttons in sidebar when active
; main             = main bg
; main-secondary   = bg color of selected song rows, bg color of artist/track cards
; sidebar          = sidebar bg
; player           = player bg
; card             = popup-card bg
; shadow           = all shadows
; button           = playlist buttons bg in sidebar, drop-down menus, now playing song, like button
; button-secondary = download and options button
; button-active    = hover on song selected
; button-disabled  = seekbar bg, volume bar bg, scrollbar
; nav-active       = sidebar buttons bg
; play-button      = color of main play button in main field
; tab-active       = button bg in main field (playlists, podcasts, artists, albums)
; notification     = notification ('Added to liked songs' etc.)
; playback-bar     = seekbar fg, volume bar fg, main play/pause button
; misc             = miscellaneous
