general {
    col.active_border = rgba(C8D2E3ff) rgba(293852ff) 45deg
    col.inactive_border = rgba(1E3949ff) rgba(475B75ff) 45deg
}

group {
    col.border_active = rgba(C8D2E3ff) rgba(293852ff) 45deg
    col.border_inactive = rgba(1E3949cc) rgba(475B75cc) 45deg
    col.border_locked_active = rgba(0E0E0Dff) rgba(070706ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
