general {
    col.active_border = rgba(076978ff) rgba(CCF8FFff) 45deg
    col.inactive_border = rgba(F3E1BBff) rgba(95A67Dff) 45deg
}

group {
    col.border_active = rgba(076978ff) rgba(CCF8FFff) 45deg
    col.border_inactive = rgba(F3E1BBcc) rgba(95A67Dcc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(FFFFFFff) 45deg
    col.border_locked_inactive = rgba(060607cc) rgba(111112cc) 45deg
}
