general {
    col.active_border = rgba(433A51ff) rgba(E0CCFFff) 45deg
    col.inactive_border = rgba(F9DDF1ff) rgba(B79FC0ff) 45deg
}

group {
    col.border_active = rgba(433A51ff) rgba(E0CCFFff) 45deg
    col.border_inactive = rgba(F9DDF1cc) rgba(B79FC0cc) 45deg
    col.border_locked_active = rgba(F3F3F2ff) rgba(FFFFFFff) 45deg
    col.border_locked_inactive = rgba(030303cc) rgba(0D0D0Ccc) 45deg
}
